### ISSUE TITLE
Cleanup/Performance Comments on Parameters and Returns

### ISSUE THREAD

**Issue by amirroth** [bigladder/btwxt#23]
I have noticed some improper use of value and reference for parameters and return values. There are multiple instances of each of these and I will point out a few of them in this one umbrella issue.

If an object needs to be passed as an input argument to a function, it should be passed by `const` reference (or pointer) to avoid making a deep copy. This is true for traditional objects (e.g., `struct`, `class`) but also for containers like `std::vector` and `std::string`. For example:

```cpp
typedef void (*BtwxtCallbackFunction)(const MsgLevel messageType, const std::string message, void *contextPtr);
```

This callback will make a local deep copy of the `message` argument.  And:

```cpp
double get_value_at_target(std::vector<double> target, std::size_t table_index);
```

Will make a deep copy of `target`. That may be the intent here (hard to tell), but if it is then it should be done explicitly with the function by passing `target` by `const &` and then doing something like `std::vector<double> copy_of_target = target;`. 

Similarly, objects should be returned by `&` or `const &` if possible, i.e., if they are not created within the function and have a lifetime that extends beyond the creating function and their intended use. A good potential example is here: 

```cpp
std::vector<double> get_current_target();
```

Conversely, scalar arguments should be passed by value. Passing scalars by reference is only needed if the function will overwrite the value. Otherwise, you are just adding dereferences and making life more difficult for the compiler. A good example is here: 

```cpp
 double get_spacing_multiplier(const std::size_t &flavor, const std::size_t &index);
```

There are a handful of other examples of each kind of problem. Mostly of the first two.

**Comment by chipbarnaby** [comment]
Agree.  Only possible quibble is that std::string message should perhaps be string_view.  I believe either a string literal or a string can be passed via string_view with minimal overhead.  To be confirmed.

Some of the indicated changes may break calling code.  That may be minimal, since call by reference is identical to call by value on the caller side.  The uses of btwxt are reasonably minimal at the moment (right?), so it may be OK to make limited breaking changes.

**Comment by amirroth** [comment]
You are correct re: `std::string_view`. And in that case, the parameter should be past by value because `std::string_view` is itself essentially a reference (it's an iterator) and passing a reference by reference is frowned upon by the Stackerati. 

The changes should not break calling code. EnergyPlus uses btwxt for Table:Lookup curve objects. I don't know where else it is used. I assume CSE.

**Comment by chipbarnaby** [comment]
Yes, CSE.

I just traced through get_values_at_target() and, as expected, does a copy constructor call from its internal results vector to generate the return vector.

If the return were changed to const vector<double>&, there would still be copying on the caller side to extract the values from  btwxt's internal vector.  It would probably be better to have the caller to own the results vector.

However, there seems to be some state within btwxt that implies it should own current results (perhaps?).  Not clear what the benefits of that are, maybe a bunch of copies are worth the price.

**Comment by amirroth** [comment]
Well, there is probably no way to avoid the copy from the client to whatever data structure it is using from a btwxt structure, but at the very least you should avoid copies inside btwxt. You don't want to do a btwxt-10X in 20 years.

**Comment by tanaya-bigladder** [comment]
There are certainly a lot of inconsistencies with regard to const-correctness in many parts of btwxt; a lot of functions _do_ pass vectors by const &, but inexplicably, some don't. A PR will be posted shortly with these fixed (and functions also labeled const when indicated, such as getters.)
As for returned values, I think we should be a bit circumspect about avoiding copies by rule. The example of get_results() is actually a prime candidate for suspending the rule in order to prevent client code from accidentally storing a mutable value. For example, if we had function signature `const std::vector<double>& get_result()`, then 
`const auto res = get_result();` wouldn't cause problems, but
`const auto& res = get_result()`, `res` reflects the latest internal state of the interpolator at all times, even after the interpolation result it requested is no longer valid. I'd suggest that in this case, preventing the user inadvertently shooting themselves in the foot is worth the cost of a mandatory copy.

**Comment by amirroth** [comment]
> I'd suggest that in this case, preventing the user inadvertently shooting themselves in the foot is worth the cost of a mandatory copy.

I'm all for avoiding inadvertent shootings, but it would be better to minimize unnecessary copies while providing this type of protection. Safety v. performance is a false choice. Are you relying on RVO to provide performance?

**Comment by tanaya-mankad** [comment]
Addressed as part of  https://github.com/NREL/EnergyPlus/issues/10163.
